Fix #15 - relative paths without __dirname
forwards-long-jump/discotron pull request #19
Opened 2019-10-14 17:40 UTC by RedMser

Fix #15 

`require` never should use __dirname, so it was removed there.

Not sure about the other uses, need feedback on these proposals:

- Always work off of the working directory as the base. Don't assume where things are based on what we expect the cwd to be.
- As such, would it make more sense to have the `dashboard` and `models` folders based off of __dirname, while `repositories` is in the cwd?

2019-10-14 20:19 UTC, Blatoy requested changes

2019-10-14 20:19 UTC, Blatoy commented on bot/classes/repository.js
> +            fs.readdirSync("../repositories/" + this._folderName + "/plugins").forEach(file => {
I'm not sure changing the __dirname here is a good thing, my initial plan was to remove it from the require() since it's not necessary there.

2019-10-15 13:01 UTC, RedMser commented
Reverted the non-require related changes, which should be tackled in #20 instead.

2019-10-15 13:13 UTC, Blatoy approved these changes

2019-10-15 13:13 UTC, merged