Refactor clean code
forwards-long-jump/discotron pull request #29
Opened 2019-10-16 16:55 UTC by Blatoy

Fix #9

2019-10-16 17:45 UTC, RedMser requested changes

2019-10-16 17:45 UTC, RedMser commented on dashboard/src/models/user.js
>       */
@returns missing

2019-10-16 17:45 UTC, RedMser commented on dashboard/src/models/user.js
> +     * @param {string} tag Called tag, should be discriminator. FIXEME!
Didn't you want to fix exactly this problem with this PR? xd

2019-10-16 17:45 UTC, RedMser commented on dashboard/src/models/channel.js
> +     * @returns {string} Channel type (voice, text, category)
Maybe make it clear what the values of this string can be? Since at line 9 (the ctor docs), there's different words used.

2019-10-16 17:45 UTC, RedMser commented on dashboard/src/controllers/plugin-list-controller.js
> +	 * @constructortructor
Did you middleclick in vscode? xd

2019-10-16 17:45 UTC, RedMser commented on dashboard/src/controllers/login-controller.js
> +            document.querySelector("#login > div > div > div > p:nth-child(2)").textContent = "Bot installation is not complete, please check the installation " +
Why not just give the element an id and call it a day... :C

2019-10-16 17:45 UTC, RedMser commented on dashboard/src/controllers/bot-status-controller.js
> +			}).then((data) => {}).catch(console.error);
Remove empty "then".

2019-10-16 17:45 UTC, RedMser commented on dashboard/index.html
> +                <li class="header">Server admins settings</li>
"admins" -> "admin"
idk the grammar rule but you should change it.

2019-10-16 17:45 UTC, RedMser commented on bot/webserver.js
> + * Server the dashboard, login and models folders
"Server" -> "Serve"

2019-10-16 17:45 UTC, RedMser commented on bot/index.js
> +    // Handle disconnecting the bot gracefuly
"gracefuly" -> "gracefully" (im so sorry xd)

2019-10-16 17:45 UTC, RedMser commented on bot/discotron.js
> +        }).catch(Logger.err);
I'm no js promise expert, but isn't it better to be a chain? So you should do x.then(() => y).then(() => z).catch(...)?

2019-10-16 17:45 UTC, RedMser commented on bot/classes/user-role.js
>          });
Oh god... Like mentioned somewhere else, it seems to me like you should chain .then() calls and just have a single .catch(...) at the end of it all! That way, there's no dumb nesting, and an exception cancels the whole chain with a single catch instead of multiple like here.

2019-10-16 17:45 UTC, RedMser commented on bot/classes/spam-user.js
> +     * Applies "health renegeration" and return if the user is still "dead"
"renegeration" -> "regeneration"

2019-10-16 17:45 UTC, RedMser commented on bot/classes/login.js
> + * @returns {Promise} resolve() called when database insert is succesful
"succesful" -> "successful"

2019-10-16 23:31 UTC, Blatoy commented on dashboard/src/models/user.js
> +     * @param {string} tag Called tag, should be discriminator. FIXEME!
Oops

2019-10-16 23:34 UTC, Blatoy commented on dashboard/src/controllers/login-controller.js
> +            document.querySelector("#login > div > div > div > p:nth-child(2)").textContent = "Bot installation is not complete, please check the installation " +
Rushing to reach a deadline did that kind of stuff >:

2019-10-17 01:45 UTC, Blatoy commented on bot/classes/user-role.js
>          });
Yes in this case and in the other you mentioned it should be changed, I'll also check where else it can also be fixed when it is less late

2019-10-17 19:53 UTC, RedMser approved these changes

2019-10-17 19:54 UTC, merged