Update ESLint rules
forwards-long-jump/discotron pull request #92
Opened 2020-02-19 15:14 UTC by RedMser

- Based on PR review, add `spaced-comment` and `no-implicit-coercion` as errors.
- Add custom rule that enforces the casing of `TODO` comments.
- Fix issues caused by the rule changes and errors that existed prior to these changes.

2020-02-19 20:38 UTC, Blatoy requested changes

2020-02-19 20:38 UTC, Blatoy commented on .github/workflows/eslint-action.yml
> +      - uses: actions-hub/stylelint@v1.1.2
As you mentioned, this action runs `npm install` with scripts enabled which breaks the testing process. Maybe there is a way to run it with `--ignore-script` ?

2020-02-19 20:38 UTC, Blatoy commented on .github/workflows/eslint-action.yml
>          with:
We could probably rename the file to linting-actions.yml

2020-02-20 15:57 UTC, RedMser commented
Gonna redo this one, we want clean history :)

2020-02-20 15:57 UTC, closed without merging